export const MOVIES_LOADING = 'MOVIES_LOADING'
export const MOVIES_LOADING_SUCCESS = 'MOVIES_LOADING_SUCCESS'
export const MOVIES_LOADING_ERROR = 'MOVIES_LOADING_ERROR'
export const FETCHING_MOVIES = 'FETCHING_MOVIES'
export const FETCH_MOVIES_INIT = 'FETCH_MOVIES_INIT'

//movie detail

export const MDETAIL_LOADING = 'MDETAIL_LOADING'
export const MDETAIL_LOADING_SUCCESS = 'MDETAIL_LOADING_SUCCESS'
export const MDETAIL_ERROR = 'MDETAIL_ERROR'